const CHANGE_NAME = "CHANGE_NAME";
const CHANGE_CATEGORYID = "CHANGE_CATEGORYID";
const CHANGE_CATEGORYNAME = "CHANGE_CATEGORYNAME";
const CHANGE_SCORE = "CHANGE_SCORE";
const CHANGE_TOTALSCORE = "CHANGE_TOTALSCORE";
const CHANGE_GAMESTATUS = "CHANGE_GAMESTATUS";
const UPDATE_GAMEPOINT = "UPDATE_GAMEPOINT";
export {
  CHANGE_NAME,
  CHANGE_CATEGORYID,
  CHANGE_CATEGORYNAME,
  CHANGE_SCORE,
  CHANGE_TOTALSCORE,
  CHANGE_GAMESTATUS,
  UPDATE_GAMEPOINT
};
